spring:
  profiles:
    active: prod
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 5000
  datasource:
    url: jdbc:mysql://localhost:3306/springboottest?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: '072077'
    driver-class-name: com.mysql.cj.jdbc.Driver
  druid:
    filters: stat,wall,slf4j,config
    max-active: 100
    initial-size: 1
    max-wait: 60000
    min-idle: 1
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: select 'x'
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-open-prepared-statements: 50
    max-pool-prepared-statement-per-connection-size: 20

app:
  info: this is dev
  auther: kven
  emal: 453546138@qq.com

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.wlxy.example.model

logging:
  level:
    org.wlxy.example.dao : debug

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

